services:
  postgres:
    image: postgres:15
    container_name: pg-orderdb
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  order-service:
    build: ./order-service
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - restaurant-service
      - accounting-service
    networks:
      - backend

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8091:8091"
    networks:
      - backend

  accounting-service:
    build: ./accounting-service
    ports:
      - "8092:8092"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
