services:
  postgres:
    image: postgres:15
    container_name: pg-orderdb
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fooddelivery-net

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP (per i microservizi)
      - "15672:15672"   # Management UI (visita http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fooddelivery-net

volumes:
  pgdata:
  rabbitmq_data:

networks:
  fooddelivery-net:
    driver: bridge