server:
  port: ${SERVER_PORT:8093}

spring:
  application:
    name: kitchen-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver      # se passi ad un RDBMS vero cambia driver e dialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false                       # in prod di solito lo disattivi
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

logging:
  level:
    root: INFO
    it.unito.kitchenservice: INFO         # DEBUG solo quando serve

app:
  rabbitmq:
    exchange: ${APP_RABBITMQ_EXCHANGE:fooddelivery.exchange}
    queue:
      prepare-ticket: ${APP_RABBITMQ_QUEUE_PREPARE_TICKET:kitchen.prepare-ticket}
    routingkey:
      prepare-ticket: ${APP_RABBITMQ_ROUTINGKEY_PREPARE_TICKET:rk.order.prepare-ticket}
      ready-ticket: ${APP_RABBITMQ_ROUTINGKEY_READY_TICKET:rk.kitchen.ready-ticket}
