server:
  port: 8090

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Usa 'validate' o 'none' in produzione
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    it.unito.orderservice: DEBUG

services:
  restaurant:
    url: http://restaurant-service:8091
  accounting:
    url: http://accounting-service:8092