server:
  port: 8090 # Deve combaciare con EXPOSE nel Dockerfile e con docker-compose

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/order_db # "postgres" è il nome del servizio nel docker-compose
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Usa 'validate' o 'none' in produzione
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    it.unito.orderservice: DEBUG