server:
  port: 8090

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  restaurant:
    url: http://localhost:8091
  accounting:
    url: http://localhost:8092

logging:
  level:
    root: INFO
    it.unito.orderservice: DEBUG
