apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-service
  namespace: fooddelivery
  labels:
    app: accounting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-service
  template:
    metadata:
      labels:
        app: accounting-service
    spec:
      containers:
        - name: accounting-service
          image: fooddelivery/accounting-service:latest # La nostra immagine locale
          imagePullPolicy: IfNotPresent # Fondamentale per usare l'immagine locale
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT # Già presente nel Dockerfile, ma può essere sovrascritto qui
              value: "8092"