apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fooddelivery
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fooddelivery/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT # Già definito nel Dockerfile, ma per chiarezza
              value: "3000"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://fooddelivery.192.168.49.2.nip.io/api"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10