apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fooddelivery
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15 # Immagine ufficiale da Docker Hub
          imagePullPolicy: IfNotPresent # Tenta di usare l'immagine locale se presente
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          # Readiness e Liveness probes sono importanti per la stabilità
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - user # Usa il nome utente dal secret
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - user
            initialDelaySeconds: 45
            periodSeconds: 20
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc