apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: fooddelivery
  labels:
    app: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: fooddelivery/restaurant-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "8091"