apiVersion: v1
kind: Service
metadata:
  name: accounting-service # Nome DNS interno
  namespace: fooddelivery
spec:
  selector:
    app: accounting-service
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP