apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fooddelivery
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000       # Porta esposta all'interno del cluster
      targetPort: 3000 # Porta del container
  type: NodePort
