apiVersion: v1
kind: Service
metadata:
  name: kitchen-service # Nome DNS interno
  namespace: fooddelivery
spec:
  selector:
    app: kitchen-service
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP