apiVersion: v1
kind: Service
metadata:
  name: restaurant-service # Nome DNS interno
  namespace: fooddelivery
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP